<?php 
$selectedDocuments = explode(',', $note['document']);
?>

<div class="row mt-5">
  <div class="col-md-12">
    <h5 class="text-muted">
      <small>
        <span>
<?php if ($type == 'done-work') : ?>
      Travail réalisé en <?php echo $context->localize($context->getConfig('student/property/school_subject')['modalities'][$note['subject']]) ?> avec le groupe <?php echo $group ?> le 
<?php elseif ($type == 'todo-work') : ?>
      Travail à faire en <?php echo $context->localize($context->getConfig('student/property/school_subject')['modalities'][$note['subject']]) ?> par le groupe <?php echo $group ?> pour le 
<?php else : ?>
      Événement en <?php echo $context->localize($context->getConfig('student/property/school_subject')['modalities'][$note['subject']]) ?> par le groupe <?php echo $group ?> le 
<?php endif;?> 
      <input type="text" id="target_date-<?php echo $type ?>" value="<?php echo $context->decodeDate($note['target_date']) ?>">
          </span>
        </small>
    </h5>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="editable" id="observations-<?php echo $type ?>"><?php echo $note['observations'] ?></div>
  </div>
</div>

<?php if (in_array($requestType, ['GET']) && $statusCode == '200') : ?>

<div id="teacherHomeworkDocumentSelect-<?php echo $type ?>">
	<select class="mdb-select md-form" id="document-<?php echo $type ?>" multiple>
	  <option value="" disabled selected><?php echo $this->translate('Select the document(s) to include', 'ppit-learning', $context->getLocale()) ?></option>
	<?php foreach ($documents as $document) : ?>
	  <option value="<?php echo $document['id'] ?>" <?php if (in_array($document['id'], $selectedDocuments)) : ?>selected<?php endif;?>><?php echo $document['name'] ?></option>
	<?php endforeach;?>
	</select>
	<label class="mdb-main-label"><?php echo $this->translate('Documents', 'ppit-core', $context->getLocale()) ?></label>
</div>

<?php endif;?>

<?php if (in_array($requestType, ['POST', 'DELETE']) && $statusCode == '200') : ?>
  <div id="message">
    <h5 class="alert alert-success my-3 text-center"><?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?></h5>
  </div>

<?php else : ?>
         
<div class="row my-3">
  <div class="col-md-12">
    <div class="text-center align-middle">
      <button class="btn btn-warning" id="teacherHomeworkSubmit-<?php echo $type ?>"><?php echo $this->translate(($id) ? 'Update' : 'Add', 'ppit-core', $context->getLocale()) ?></button>
      <?php if ($id) : ?><button class="btn btn-danger" id="teacherHomeworkDelete-<?php echo $type ?>"><?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?></button><?php endif;?>
    </div>
  </div>
</div>

<?php endif;?>
