<!-- 
/**
 * PpitCore V1.0 (https://github.com/p-pit/PpitCore)
 *
 * @link      https://github.com/p-pit/PpitCore
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitCore/blob/master/license.txt GNU-GPL license
 */
-->

<style>
.homework-document-drop {
  padding: 10px;
  border: 1px solid #aaaaaa;
}
</style>

  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="text-uppercase"><small>Planning <i class="fas fa-chevron-right"></i> Detail</Small></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" title="<?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?>">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modalFormBody">
        <div class="container">
      
          <div class="event-nav-target" id="event-nav-target-appointment">
 
      <ul class="nav nav-tabs md-tabs nav-justified primary-color">
        <li class="nav-item"><a class="nav-link active" id="document-tab-md" data-toggle="tab" href="#document-md" role="tab" aria-controls="document-md"><?php echo $this->translate('Contenu pédagogique', 'ppit-core', $context->getLocale())?></a></li>

<!-- user_story: Absence and lateness can be notified only on slots that are not grouped (on only 1 date) -->
<?php if ($event->end_date == $event->begin_date) : ?>
        <li class="nav-item"><a class="nav-link" id="absence-tab-md" data-toggle="tab" href="#absence-md" role="tab" aria-controls="absence-md"><?php echo $this->translate('Retards et absentéisme', 'ppit-core', $context->getLocale())?></a></li>
<?php endif;?>
      </ul>
 
      <div class="tab-content card pt-5">
        <div class="tab-pane fade show active" id="document-md" role="tabpanel" aria-labelledby="document-tab-md">
     
<h5 class="modal-title text-muted text-center" id="modalFormLabel">
    <strong><?php if ($event->property_3) echo $context->localize($eventConfig['property_3']['modalities'][$event->property_3]) . ', ' ?></strong>
    <?php echo $event->caption ?>&nbsp;&nbsp;
    <small>
      <i class="far fa-clock"></i> <?php echo substr($date, 8, 2) ?>/<?php echo substr($date, 5, 2) ?>
      (<?php echo substr($event->begin_time, 0, 2) . 'H' . substr($event->begin_time, 3, 2) ?>&mdash;<?php echo substr($event->end_time, 0, 2) . 'H' . substr($event->end_time, 3, 2) ?>)
    </small>&nbsp;&nbsp;
    <small><i class="fas fa-map-marker-alt"></i> <?php echo $event->location ?></small>
</h5>

<hr /> <!-- Trait de séparation -->

          <div class="row">
            <div class="col-md-12">
              <h5 class="text-center text-muted"><small>Mes documents</small></h5>
            </div>
          </div>

          <div class="row" id="document-list"></div>

          <hr>

          <div id="teacher-homework-done-work"></div>

          <div id="teacher-homework-todo-work"></div>
         
          <div class="row my-3">
            <div class="col-md-12">
              <div class="text-center align-middle text-muted"><button class="btn btn-warning" id="teacherHomeworkSubmit"><?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?></button></div>
            </div>
          </div>

        </div>
        <div class="tab-pane fade" id="absence-md" role="tabpanel" aria-labelledby="absence-tab-md"></div>
      </div>
 
          </div>
        </div>
      </div>
    </div>
  </div>
      